version: '3.4'
services:
  rasa-x:
    image: dash-ecomm:latest
    build: "./"
    restart: always
    working_dir: /app
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./src:/app/src
    command: ["poetry","run","rasa","x", "--no-prompt"]
    ports:
      - '5005:5005'
      - '5002:5002'
    networks:
      - all

  rasa-actions:
    build: "./"
    image: dash-ecomm:latest
    restart: always
    working_dir: /app
    volumes:
      - ./actions:/app/actions
      - ./src:/app/src
    command: ["poetry","run","rasa","run","actions"]
    networks:
      - all

  callback-server:
    build: "./"
    image: dash-ecomm:latest
    restart: always
    volumes:
      - ./src:/app/src
    command: ["poetry","run","python", "-m", "dash_ecomm.callback_server"]
    networks:
      - all


  duckling:
    image: rasa/duckling:latest
    networks:
      - all

  demo:
    build: "./"
    image: dash-ecomm:latest
    working_dir: /app/demo/local
    volumes:
      - ./demo:/app/demo
    command: ["poetry","run", "python", "-m", "http.server", "7000"]
    ports:
      - '7000:7000'
    networks:
      - all

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - all

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - all

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - all

  kib01:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - all

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
