orders:
-
   id: "DASH123450"
   order_date: "2021-03-12"
   order_number: 123456
   order_email: "not-registered@me.com"
   product_name: 'Shoes'
   color: 'blue'
   size: '9'
   status: "shipped"
   image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&w=1000&q=80"
-
   id: "DASH123451"
   order_date: "2021-03-12"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   product_name: 'Shoes'
   color: 'blue'
   size: '9'
   status: "canceled"
   image_url: "https://assets.ajio.com/medias/sys_master/root/h5a/h59/13018715881502/-1117Wx1400H-460342492-blue-MODEL.jpg"
-
   id: "DASH123452"
   order_date: "2021-03-11"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   product_name: 'Shoes'
   color: 'Blue'
   size: '9'
   status: "shipped"
   image_url: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500"
-
   id: "DASH123453"
   order_date: "2021-03-11"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   product_name: 'Shoes'
   color: 'Pink'
   size: '9'
   status: "returning"
   returnable: false
   image_url: "https://image.shutterstock.com/image-photo/pair-pink-sport-shoes-on-260nw-228691018.jpg"
-
   id: "DASH123454"
   order_date: "2021-03-11"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   product_name: 'Shoes'
   color: 'Pink'
   size: '9'
   status: "pending"
   image_url: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500"
-
   id: "DASH123455"
   order_date: "2021-01-05"
   order_number: 123457
   order_email: "ayushman@neuralspace.ai"
   product_name: 'Shoes'
   color: 'black'
   size: "10"
   status: "order pending"
   image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&w=1000&q=80"
-
   id: "DASH123456"
   order_date: "2021-01-05"
   order_number: 123458
   order_email: "dishant@neuralspace.ai"
   product_name: 'Shoes'
   color: "Navy blue"
   size: '10'
   status: 'order pending'
   image_url: "https://i02.appmifile.com/363_operator_in/13/10/2020/c7bde508f128d7b1fd10a224d18a5333.png"
-
   id: "DASH123457"
   order_date: "2021-01-05"
   order_number: 123459
   order_email: "dishant@neuralspace.ai"
   product_name: 'Shoes'
   color: "gray"
   size: '11'
   status: 'delivered'
   returnable: 'False'
   image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYQal2Wt0rgcL_9IIPCHwBr5Z_3ilg5rv0xQ&usqp=CAU"
-
   id: "DASH123458"
   order_date: "2021-01-05"
   order_number: 123459
   order_email: "dishant@neuralspace.ai"
   product_name: 'Shoes'
   color: "gray"
   size: '11'
   status: 'delivered'
   returnable: true
   image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCytvY7-SDfxRIfcX4IuzzTdrq_15WV9d3Vw&usqp=CAU"
-
   id: "DASH123459"
   order_date: "2021-01-05"
   order_number: 123459
   order_email: "dishant@neuralspace.ai"
   product_name: 'Shoes'
   color: "gray"
   size: '11'
   status: 'shipped'
   image_url: "https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/09/hoka.png"
-
   id: "DASH123460"
   order_date: "2021-01-05"
   order_number: 123459
   order_email: "dishant@neuralspace.ai"
   product_name: 'Shoes'
   color: "gray"
   size: '11'
   status: 'shipped'
   image_url: "https://cdnmedia.dsc-cricket.com/media/catalog/product/cache/67ee89799642c567a71fc92f3699d937/d/s/dsc-zooter-cricket-shoes-red.jpg"
-
   id: "DASH123461"
   order_date: "2021-01-05"
   order_number: 123459
   order_email: "dishant@neuralspace.ai"
   product_name: 'Shoes'
   color: "gray"
   size: '11'
   status: 'shipped'
   image_url: "https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/268453-Best_Running_Shoes_for_Flat_Feet-1296x728-header-1296x728.jpg?w=1155&h=1528"

products:
-
   product_name: "Shoes"
   size: '7'
   color: 'blue'
-
   product_name: 'Shoes'
   size: '8'
   color: 'blue'
-
   product_name: 'Shoes'
   size: '9'
   color: 'blue'
-
   product_name: "Shoes"
   size: '10'
   color: 'blue'
-
   product_name: "Shoes"
   size: '11'
   color: 'blue'
-
   product_name: "Shoes"
   size: '12'
   color: 'blue'
-
   product_name: "Shoes"
   size: "7"
   color: "black"
-
   product_name: "Shoes"
   size: '8'
   color: "black"
-
   product_name: "Shoes"
   size: "9"
   color: "black"
-
   product_name: "Shoes"
   size: "10"
   color: "black"

users:
   "dishant@neuralspace.ai":
      id: 0
      user_email: "dishant@neuralspace.ai"
      first_name: "Dishant"
      last_name: "Gandhi"
      otp: "1234"
      no_of_orders : 6
   "ayushman@neuralspace.ai":
      id: 1
      user_email: "ayushman@neuralspace.ai"
      first_name: "Ayushman"
      last_name: "Dash"
      otp: "5678"
      no_of_orders : 1
   "pooja@neuralspace.ai":
      id: 2
      user_email: "pooja@neuralspace.ai"
      first_name: "Pooja"
      last_name: "Mishra"
      otp: "9876"
      no_of_orders : 4