orders:
-
   id: 0
   order_date: "2021-03-12"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   name: 'shoes'
   color: 'blue'
   size: '9'
   status: "canceled"
   image_url: "some/image/url"
-
   id: 1
   order_date: "2021-03-11"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   name: 'shoes'
   color: 'blue'
   size: '9'
   status: "shipped"
   image_url: "some/image/url"
-
   id: 2
   order_date: "2021-03-11"
   order_number: 123456
   order_email: "pooja@neuralspace.ai"
   name: 'shoes'
   color: 'blue'
   size: '9'
   status: "delivered"
   image_url: "some/image/url"
-
   id: 3
   order_date: "2021-01-05"
   order_number: 123457
   order_email: "ayushman@neuralspace.ai"
   name: 'shoes'
   color: 'black'
   size: "10"
   status: "order pending"
   image_url: "some/image/url"
-
   id: 4
   order_date: "2021-01-05"
   order_number: 123458
   order_email: "dishant@neuralspace.ai"
   name: 'shoes'
   color: "gray"
   size: '11'
   status: 'returning'
   image_url: "some/image/url"

products:
-
   name: "shoes"
   size: '7'
   color: 'blue'
-
   name: 'shoes'
   size: '8'
   color: 'blue'
-
   name: 'shoes'
   size: '9'
   color: 'blue'
-
   name: "shoes"
   size: '10'
   color: 'blue'
-
   name: "shoes"
   size: '11'
   color: 'blue'
-
   name: "shoes"
   size: '12'
   color: 'blue'
-
   name: "shoes"
   size: "7"
   color: "black"
-
   name: "shoes"
   size: '8'
   color: "black"
-
   name: "shoes"
   size: "9"
   color: "black"
-
   name: "shoes"
   size: "10"
   color: "black"

users:
   dishant@neuralspace.ai:
      id: 0
      email: "dishant@neuralspace.ai"
      first_name: "Dishant"
      last_name: "Gandhi"
      otp: 1234
   ayushman@neuralspace.ai:
      id: 1
      email: "ayushman@neuralspace.ai"
      first_name: "Ayushman"
      last_name: "Dash"
      otp: 5678
   pooja@neuralspace.ai:
      id: 2
      email: "pooja@neuralspace.ai"
      first_name: "Pooja"
      last_name: "Mishra"
      otp: 9876