orders:
- color: blue
  id: DASH123450
  image_url: https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&w=1000&q=80
  order_date: '2021-03-12'
  order_email: not-registered@me.com
  order_number: 123456
  product_name: Shoes
  refunded: false
  returnable: false
  size: '9'
  status: shipped
- color: blue
  id: DASH123451
  image_url: https://assets.ajio.com/medias/sys_master/root/h5a/h59/13018715881502/-1117Wx1400H-460342492-blue-MODEL.jpg
  order_date: '2021-03-12'
  order_email: pooja@neuralspace.ai
  order_number: 123456
  product_name: Shoes
  refunded: true
  returnable: false
  size: '9'
  status: canceled
- color: Blue
  id: DASH123452
  image_url: https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500
  order_date: '2021-03-11'
  order_email: pooja@neuralspace.ai
  order_number: 123456
  product_name: Shoes
  refunded: false
  returnable: false
  size: '9'
  status: shipped
- color: Pink
  id: DASH123453
  image_url: https://image.shutterstock.com/image-photo/pair-pink-sport-shoes-on-260nw-228691018.jpg
  order_date: '2021-03-11'
  order_email: pooja@neuralspace.ai
  order_number: 123456
  product_name: Shoes
  refunded: false
  returnable: false
  size: '9'
  status: returning
- color: Pink
  id: DASH123454
  image_url: https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500
  order_date: '2021-03-11'
  order_email: pooja@neuralspace.ai
  order_number: 123456
  product_name: Shoes
  refunded: false
  returnable: false
  size: '9'
  status: order pending
- color: black
  id: DASH123455
  image_url: https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&w=1000&q=80
  order_date: '2021-01-05'
  order_email: ayushman@neuralspace.ai
  order_number: 123457
  product_name: Shoes
  refunded: false
  returnable: false
  size: '10'
  status: order pending
- color: Navy blue
  id: DASH123456
  image_url: https://i02.appmifile.com/363_operator_in/13/10/2020/c7bde508f128d7b1fd10a224d18a5333.png
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123458
  product_name: Shoes
  refunded: false
  returnable: false
  size: '10'
  status: order pending
- color: gray
  id: DASH123457
  image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYQal2Wt0rgcL_9IIPCHwBr5Z_3ilg5rv0xQ&usqp=CAU
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123459
  product_name: Shoes
  refunded: false
  returnable: true
  size: '11'
  status: order pending
- color: gray
  id: DASH123458
  image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCytvY7-SDfxRIfcX4IuzzTdrq_15WV9d3Vw&usqp=CAU
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123459
  product_name: Shoes
  refunded: false
  returnable: false
  size: '11'
  status: returning
- color: gray
  id: DASH123459
  image_url: https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/09/hoka.png
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123459
  product_name: Shoes
  refunded: false
  returnable: false
  size: '11'
  status: shipped
- color: gray
  id: DASH123460
  image_url: https://cdnmedia.dsc-cricket.com/media/catalog/product/cache/67ee89799642c567a71fc92f3699d937/d/s/dsc-zooter-cricket-shoes-red.jpg
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123459
  product_name: Shoes
  refunded: false
  returnable: false
  size: '11'
  status: shipped
- color: gray
  id: DASH123443
  image_url: https://cdnmedia.dsc-cricket.com/media/catalog/product/cache/67ee89799642c567a71fc92f3699d937/d/s/dsc-zooter-cricket-shoes-red.jpg
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123459
  product_name: Shoes
  refunded: false
  returnable: false
  size: '11'
  status: returning
- color: gray
  id: DASH123461
  image_url: https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/01/268453-Best_Running_Shoes_for_Flat_Feet-1296x728-header-1296x728.jpg?w=1155&h=1528
  order_date: '2021-01-05'
  order_email: dishant@neuralspace.ai
  order_number: 123459
  product_name: Shoes
  refunded: false
  returnable: false
  size: '11'
  status: delivered
products:
- color: blue
  product_name: Shoes
  size: '7'
- color: blue
  product_name: Shoes
  size: '8'
- color: blue
  product_name: Shoes
  size: '9'
- color: blue
  product_name: Shoes
  size: '10'
- color: blue
  product_name: Shoes
  size: '11'
- color: blue
  product_name: Shoes
  size: '12'
- color: black
  product_name: Shoes
  size: '7'
- color: black
  product_name: Shoes
  size: '8'
- color: black
  product_name: Shoes
  size: '9'
- color: black
  product_name: Shoes
  size: '10'
users:
  ayushman@neuralspace.ai:
    first_name: Ayushman
    id: 1
    last_name: Dash
    no_of_orders: 1
    otp: '5678'
    user_email: ayushman@neuralspace.ai
  dishant@neuralspace.ai:
    first_name: Dishant
    id: 0
    last_name: Gandhi
    no_of_orders: 6
    otp: '1234'
    user_email: dishant@neuralspace.ai
  pooja@neuralspace.ai:
    first_name: Pooja
    id: 2
    last_name: Mishra
    no_of_orders: 4
    otp: '9876'
    user_email: pooja@neuralspace.ai
